spring:
  application:
    name: chirp

  data:
    redis:
      host: "redis-15401.c304.europe-west1-2.gce.cloud.redislabs.com"
      password: ${REDIS_PASSWORD}
      username: "default"
      port: 15401
      connect-timeout: 5000ms
      timeout: 2000ms

  datasource:
    url: jdbc:postgresql://db.yvmwtlxnxywgbhndamjs.supabase.co:5432/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  mail:
    port: 587
    password: ${MAILGUN_PASSWORD} # Spring mail will use this password to authenticate with the mail server.
    properties:
      mail:
        SMTP:
          auth: true
          STARTTLS:
            enable: true

  rabbitmq:
    host: dog.lmq.cloudamqp.com
    password: ${RABBITMQ_PASSWORD}
    username: niymxvym
    ssl:
      enabled: true
    virtual-host: niymxvym
    listener:
      simple:
        # acknowledge-mode is what you can use to define how your rabbitmq listeners should handle events.
        # RabbitMQ is also responsible to guarantee delivery of events. If an event fails to be processed, RabbitMQ will automatically requeue it.
        # auto: Acknowledge messages automatically after they are processed.
        # manual: Acknowledge messages manually after they are processed.
        acknowledge-mode: auto
        # concurrency is the number of threads that will be used to process messages. Limitation from the free plan to use only 1 thread. In production with a paid plan this number can be increased.
        # max-concurrency is the maximum number of threads that will be used to process messages.
        # prefetch is the number of messages that will be prefetched from the queue (number of messages that haven't been processed yet).
        # default-requeue-rejected is whether to requeue messages that are rejected.
        concurrency: 1
        max-concurrency: 3
        prefetch: 10
        default-requeue-rejected: true
        # retry is the number of times a message will be retried before being discarded.
        # enabled true means that retries will be enabled.
        # initial-interval is the initial time interval between retries.
        # max-interval is the maximum time interval between retries.
        # multiplier is the multiplier for the time interval between retries.
        # max-retries is the maximum number of retries.
        retry:
          enabled: true
          initial-interval: 1000ms
          max-interval: 10000ms
          multiplier: 2
          max-retries: 3

jwt:
  secret: ${JWT_SECRET_BASE64}

chirp:
  email:
    from: "mail@chirp.com"
    verification:
      expiry-hours: 24
    reset-password:
      expiry-minutes: 30

nginx:
  trusted-ips:
    - "127.0.0.1" # nginx on same machine
    - "::1" # IPv6 localhost
    - "172.17.0.0/16" # nginx container IP when using Docker
    - "10.0.0.5/32" # nginx server IP (if separate machine)

supabase:
  url: "https://yvmwtlxnxywgbhndamjs.supabase.co"
  service-key: ${SUPABASE_SERVICE_KEY}

firebase:
  credentials-path: "classpath:firebase-credentials/chirp-firebase-adminsdk.json"

