spring:
  jpa:
    hibernate:
      ddl-auto: validate
  # If I want to use this in production, I need to create a real domain and get the credentials and not reuse the one from development.
  mail:
    host: smtp.mailgun.org
    username: sandboxdb81cc8bd1004b178d1cfd38d8f5cc74.mailgun.org@sandboxdb81cc8bd1004b178d1cfd38d8f5cc74.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chirp:
  rate-limit:
    ip:
      apply-limit: true