spring:
  jpa:
    hibernate:
      ddl-auto: update
  # Mailgun configuration for development environment
  mail:
    host: smtp.mailgun.org
    username: sandboxdb81cc8bd1004b178d1cfd38d8f5cc74.mailgun.org@sandboxdb81cc8bd1004b178d1cfd38d8f5cc74.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

chirp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false
  web-socket:
    allowed-origin: "http://localhost:8080"

  logging:
    level:
      com.project.chirp: DEBUG
